package com.ksondzyk.gui_swing;


import com.ksondzyk.entities.Message;
import com.ksondzyk.entities.Packet;
import com.ksondzyk.gui_swing.frames.addGroupFrame;
import com.ksondzyk.network.TCP.TCPClientThread;
import com.ksondzyk.storage.Product;
import com.ksondzyk.utilities.CipherMy;
import org.json.JSONObject;

import javax.swing.*;

public class AddProductFrame extends javax.swing.JFrame {

    /**
     * Creates new form addGroupFrame
     */
    public AddProductFrame() {
        super("Add product");
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    /**
     * initializes all the components
     */
    private void initComponents() {

        titleField = new javax.swing.JTextField();
        createGroupButton = new javax.swing.JButton();
        categoryField = new javax.swing.JTextField();
        categoryLabel = new javax.swing.JLabel();
        quantityLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        quantityField = new JSpinner();
        priceField = new JSpinner();

        setAlwaysOnTop(true);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);
        createGroupButton.setText("Додати");
        createGroupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createProductButtonActionPerformed(evt);
            }
        });

        titleLabel.setText("Title");

        categoryLabel.setText("Category");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap(64, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(titleField, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(categoryField, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(quantityField, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(priceField, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(62, 62, 62))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(titleLabel)
                                                .addGap(164, 164, 164))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(createGroupButton, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(89, 89, 89))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(categoryLabel)
                                                .addGap(159, 159, 159)).addGroup(layout.createSequentialGroup()
                                        .addComponent(priceLabel)
                                        .addGap(164, 164, 164)).addGroup(layout.createSequentialGroup()
                                        .addComponent(quantityLabel)
                                        .addGap(164, 164, 164))
                        ));

        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                               // .addContainerGap(29, Short.MAX_VALUE)
                                .addComponent(categoryLabel)
                                //.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(titleField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                //.addGap(18, 18, 18)
                                .addComponent(titleLabel)
                                .addGap(5, 5, 5)
                                .addComponent(categoryField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(priceLabel)
                              //  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(priceField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(quantityLabel)
                               // .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(quantityField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(createGroupButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>

    /**
     * proceeds to creating the group
     * @param evt
     */
    private void createProductButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        String title = titleField.getText();
        String category = categoryField.getText();
        int quantity = (int) quantityField.getValue();
        int price = (int) priceField.getValue();

        JSONObject jsonObject = new JSONObject();
        jsonObject.put("cType","2");
        jsonObject.put("type","good");
        jsonObject.put("category",category);
        jsonObject.put("title",title);
        jsonObject.put("price",price);
        jsonObject.put("quantity",quantity);


        Packet packet = new Packet((byte) 1,new Message(1,1,jsonObject.toString(),false));
        TCPClientThread tcpClientThread = new TCPClientThread(packet);
        Packet answer = tcpClientThread.send();
        String jsonString = CipherMy.decode(answer.getBMsq().getMessage());
        JSONObject responseMessage = new JSONObject(jsonString);
        int categoryId = responseMessage.getInt("categoryID");
        Product product = new Product();
        product.setName(title);
        product.setAmount(quantity);
        product.setPrice(price);
        product.setGroupID(categoryId);
        StorageFrame.addProductToList(product);
        // Storage.gr.put(name, new ProductGroup(name));
        StorageFrame.productsTable.revalidate();
        StorageFrame.productsTable.repaint();
        Storage.model.fireTableDataChanged();
        dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(com.ksondzyk.gui_swing.frames.addGroupFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(com.ksondzyk.gui_swing.frames.addGroupFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(com.ksondzyk.gui_swing.frames.addGroupFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(com.ksondzyk.gui_swing.frames.addGroupFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new addGroupFrame().setVisible(true));
    }

    // Variables declaration - do not modify
    private javax.swing.JButton createGroupButton;
    private javax.swing.JTextField titleField;
    private javax.swing.JTextField categoryField;
    private javax.swing.JSpinner quantityField;
    private javax.swing.JSpinner priceField;
    private javax.swing.JLabel quantityLabel;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JLabel categoryLabel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration
}