/*
File: removeGroupFrame.java
Author: Kate Bilorus
 */
package com.ksondzyk.gui_swing;

//import static com.company.StorageFrame.productsGroups;

public class removeGroupFrame extends javax.swing.JFrame {

    /**
     * Creates new form removeGroupFrame
     */
    public removeGroupFrame() {
        super("Видалити группу");
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    //// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deleteGroupChooser = new javax.swing.JComboBox<>();
        deleteGroupButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setAlwaysOnTop(true);
        setType(Type.POPUP);

        String[] temp = Storage.productsGroups.toArray(new String[Storage.productsGroups.size()]);
        deleteGroupChooser.setModel(new javax.swing.DefaultComboBoxModel<>(temp));

        deleteGroupButton.setText("Видалити");
        deleteGroupButton.addActionListener(evt -> deleteGroupButtonActionPerformed(evt));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(deleteGroupChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deleteGroupButton, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteGroupButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteGroupChooser))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * proceeds to deleting the group
     * @param evt
     */
    private void deleteGroupButtonActionPerformed(java.awt.event.ActionEvent evt) {
        String groupToRemove = String.valueOf(deleteGroupChooser.getSelectedItem());
        StorageFrame.deleteGroup(groupToRemove);
      //  Storage.gr.remove(groupToRemove);
        dispose();
        }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteGroupButton;
    private javax.swing.JComboBox<String> deleteGroupChooser;
    // End of variables declaration//GEN-END:variables
}
